/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthTicketsRouteImport } from './routes/_auth.tickets'
import { Route as AuthSquadsRouteImport } from './routes/_auth.squads'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthTicketsIndexRouteImport } from './routes/_auth.tickets.index'
import { Route as AuthTicketsNewRouteImport } from './routes/_auth.tickets.new'
import { Route as AuthTicketsTicketIdRouteImport } from './routes/_auth.tickets.$ticketId'
import { Route as AuthSquadsSquadIdRouteImport } from './routes/_auth.squads.$squadId'
import { Route as AuthManageUsersRouteImport } from './routes/_auth.manage.users'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTicketsRoute = AuthTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSquadsRoute = AuthSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTicketsIndexRoute = AuthTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTicketsRoute,
} as any)
const AuthTicketsNewRoute = AuthTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthTicketsRoute,
} as any)
const AuthTicketsTicketIdRoute = AuthTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AuthTicketsRoute,
} as any)
const AuthSquadsSquadIdRoute = AuthSquadsSquadIdRouteImport.update({
  id: '/$squadId',
  path: '/$squadId',
  getParentRoute: () => AuthSquadsRoute,
} as any)
const AuthManageUsersRoute = AuthManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/squads': typeof AuthSquadsRouteWithChildren
  '/tickets': typeof AuthTicketsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/manage/users': typeof AuthManageUsersRoute
  '/squads/$squadId': typeof AuthSquadsSquadIdRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/tickets/new': typeof AuthTicketsNewRoute
  '/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/squads': typeof AuthSquadsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/manage/users': typeof AuthManageUsersRoute
  '/squads/$squadId': typeof AuthSquadsSquadIdRoute
  '/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/tickets/new': typeof AuthTicketsNewRoute
  '/tickets': typeof AuthTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/squads': typeof AuthSquadsRouteWithChildren
  '/_auth/tickets': typeof AuthTicketsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/manage/users': typeof AuthManageUsersRoute
  '/_auth/squads/$squadId': typeof AuthSquadsSquadIdRoute
  '/_auth/tickets/$ticketId': typeof AuthTicketsTicketIdRoute
  '/_auth/tickets/new': typeof AuthTicketsNewRoute
  '/_auth/tickets/': typeof AuthTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/squads'
    | '/tickets'
    | '/auth/callback'
    | '/manage/users'
    | '/squads/$squadId'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/squads'
    | '/auth/callback'
    | '/manage/users'
    | '/squads/$squadId'
    | '/tickets/$ticketId'
    | '/tickets/new'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_auth/squads'
    | '/_auth/tickets'
    | '/auth/callback'
    | '/_auth/manage/users'
    | '/_auth/squads/$squadId'
    | '/_auth/tickets/$ticketId'
    | '/_auth/tickets/new'
    | '/_auth/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tickets': {
      id: '/_auth/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthTicketsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/squads': {
      id: '/_auth/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof AuthSquadsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tickets/': {
      id: '/_auth/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthTicketsIndexRouteImport
      parentRoute: typeof AuthTicketsRoute
    }
    '/_auth/tickets/new': {
      id: '/_auth/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof AuthTicketsNewRouteImport
      parentRoute: typeof AuthTicketsRoute
    }
    '/_auth/tickets/$ticketId': {
      id: '/_auth/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthTicketsTicketIdRouteImport
      parentRoute: typeof AuthTicketsRoute
    }
    '/_auth/squads/$squadId': {
      id: '/_auth/squads/$squadId'
      path: '/$squadId'
      fullPath: '/squads/$squadId'
      preLoaderRoute: typeof AuthSquadsSquadIdRouteImport
      parentRoute: typeof AuthSquadsRoute
    }
    '/_auth/manage/users': {
      id: '/_auth/manage/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof AuthManageUsersRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthSquadsRouteChildren {
  AuthSquadsSquadIdRoute: typeof AuthSquadsSquadIdRoute
}

const AuthSquadsRouteChildren: AuthSquadsRouteChildren = {
  AuthSquadsSquadIdRoute: AuthSquadsSquadIdRoute,
}

const AuthSquadsRouteWithChildren = AuthSquadsRoute._addFileChildren(
  AuthSquadsRouteChildren,
)

interface AuthTicketsRouteChildren {
  AuthTicketsTicketIdRoute: typeof AuthTicketsTicketIdRoute
  AuthTicketsNewRoute: typeof AuthTicketsNewRoute
  AuthTicketsIndexRoute: typeof AuthTicketsIndexRoute
}

const AuthTicketsRouteChildren: AuthTicketsRouteChildren = {
  AuthTicketsTicketIdRoute: AuthTicketsTicketIdRoute,
  AuthTicketsNewRoute: AuthTicketsNewRoute,
  AuthTicketsIndexRoute: AuthTicketsIndexRoute,
}

const AuthTicketsRouteWithChildren = AuthTicketsRoute._addFileChildren(
  AuthTicketsRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSquadsRoute: typeof AuthSquadsRouteWithChildren
  AuthTicketsRoute: typeof AuthTicketsRouteWithChildren
  AuthManageUsersRoute: typeof AuthManageUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSquadsRoute: AuthSquadsRouteWithChildren,
  AuthTicketsRoute: AuthTicketsRouteWithChildren,
  AuthManageUsersRoute: AuthManageUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
